"""MCQ schema and LangGraph grading."""

import asyncio
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from app.graphs.mcq_graph import _check_answer, grade_mcq_answer, try_grade_mcq_fast
from app.schemas.mcq import McqQuestion


def test_mcq_question_validates_options() -> None:
    q = McqQuestion(
        question="What is Kitab-ul-Hind?",
        options=["A book", "A city", "A ruler"],
        correct_index=0,
        explanation="It is Al-Biruni's work.",
    )
    assert q.correct_index == 0


def test_mcq_question_rejects_bad_index() -> None:
    with pytest.raises(ValueError):
        McqQuestion(
            question="Sample?",
            options=["A", "B"],
            correct_index=3,
        )


def test_check_answer_defers_feedback_to_llm() -> None:
    """Correctness is decided instantly; feedback is ALWAYS generated by the LLM."""
    out = _check_answer(
        {
            "question": "Q?",
            "options": ["A", "B"],
            "correct_index": 1,
            "selected_index": 1,
            "explanation": "Because B.",
        }
    )
    assert out["is_correct"] is True
    # feedback_ready must be False so the graph routes to the teach node.
    assert out["feedback_ready"] is False


def test_try_grade_mcq_fast_correct_returns_empty_feedback() -> None:
    """Fast path returns only the verdict; feedback is left empty for the LLM to fill."""
    out = try_grade_mcq_fast(
        options=["A", "B"],
        correct_index=1,
        selected_index=1,
        explanation="Because B.",
    )
    assert out is not None
    assert out["is_correct"] is True
    assert out["feedback"] == ""


def test_try_grade_mcq_fast_wrong_returns_empty_feedback() -> None:
    out = try_grade_mcq_fast(
        options=["A", "B"],
        correct_index=1,
        selected_index=0,
        explanation="B fits because it matches how European accounts spread through print.",
    )
    assert out is not None
    assert out["is_correct"] is False
    assert out["feedback"] == ""


def test_try_grade_mcq_fast_no_options_returns_none() -> None:
    assert try_grade_mcq_fast(options=[], correct_index=1, selected_index=0) is None


def test_grade_mcq_answer_correct_still_calls_llm() -> None:
    """Even a correct answer gets world-class LLM feedback now."""
    db = MagicMock()

    async def run() -> None:
        with patch("app.graphs.mcq_graph.complete_chat", new_callable=AsyncMock) as mock_complete:
            mock_complete.return_value = "B is right because it captures the idea.\n\nAnd that's the takeaway."
            result = await grade_mcq_answer(
                db,
                question="Q?",
                options=["A", "B"],
                correct_index=1,
                selected_index=1,
                explanation="Because B.",
                document_context="",
            )
        assert result["is_correct"] is True
        assert "B is right" in result["feedback"]
        mock_complete.assert_called_once()

    asyncio.run(run())


def test_grade_mcq_answer_wrong_uses_llm() -> None:
    db = MagicMock()

    async def run() -> None:
        with patch("app.graphs.mcq_graph.complete_chat", new_callable=AsyncMock) as mock_complete:
            mock_complete.return_value = "The correct answer is B because…\n\nYou picked A — the trap."
            result = await grade_mcq_answer(
                db,
                question="Q?",
                options=["A", "B"],
                correct_index=1,
                selected_index=0,
                explanation="",
                document_context="",
            )
        assert result["is_correct"] is False
        assert "correct answer" in result["feedback"].lower()
        mock_complete.assert_called_once()

    asyncio.run(run())
