"""MCQ schema and LangGraph grading."""

import asyncio
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from app.graphs.mcq_graph import _check_answer, grade_mcq_answer, try_grade_mcq_fast
from app.schemas.mcq import McqQuestion


def test_mcq_question_validates_options() -> None:
    q = McqQuestion(
        question="What is Kitab-ul-Hind?",
        options=["A book", "A city", "A ruler"],
        correct_index=0,
        explanation="It is Al-Biruni's work.",
    )
    assert q.correct_index == 0


def test_mcq_question_rejects_bad_index() -> None:
    with pytest.raises(ValueError):
        McqQuestion(
            question="Sample?",
            options=["A", "B"],
            correct_index=3,
        )


def test_check_answer_defers_feedback_to_llm() -> None:
    """Correctness is decided instantly; feedback is ALWAYS generated by the LLM."""
    out = _check_answer(
        {
            "question": "Q?",
            "options": ["A", "B"],
            "correct_index": 1,
            "selected_index": 1,
            "explanation": "Because B.",
        }
    )
    assert out["is_correct"] is True
    # feedback_ready must be False so the graph routes to the teach node.
    assert out["feedback_ready"] is False


def test_try_grade_mcq_fast_correct_returns_empty_feedback() -> None:
    """Fast path returns only the verdict; feedback is left empty for the LLM to fill."""
    out = try_grade_mcq_fast(
        options=["A", "B"],
        correct_index=1,
        selected_index=1,
        explanation="Because B.",
    )
    assert out is not None
    assert out["is_correct"] is True
    assert out["feedback"] == ""


def test_try_grade_mcq_fast_wrong_returns_empty_feedback() -> None:
    out = try_grade_mcq_fast(
        options=["A", "B"],
        correct_index=1,
        selected_index=0,
        explanation="B fits because it matches how European accounts spread through print.",
    )
    assert out is not None
    assert out["is_correct"] is False
    assert out["feedback"] == ""


def test_try_grade_mcq_fast_no_options_returns_none() -> None:
    assert try_grade_mcq_fast(options=[], correct_index=1, selected_index=0) is None


def test_grade_mcq_answer_correct_still_calls_llm() -> None:
    """Even a correct answer gets world-class LLM feedback now."""
    db = MagicMock()

    async def run() -> None:
        with patch("app.graphs.mcq_graph.complete_chat", new_callable=AsyncMock) as mock_complete:
            mock_complete.return_value = "B is right because it captures the idea.\n\nAnd that's the takeaway."
            result = await grade_mcq_answer(
                db,
                question="Q?",
                options=["A", "B"],
                correct_index=1,
                selected_index=1,
                explanation="Because B.",
                document_context="",
            )
        assert result["is_correct"] is True
        assert "B is right" in result["feedback"]
        mock_complete.assert_called_once()

    asyncio.run(run())


def test_grade_mcq_answer_wrong_uses_llm() -> None:
    db = MagicMock()

    async def run() -> None:
        with patch("app.graphs.mcq_graph.complete_chat", new_callable=AsyncMock) as mock_complete:
            mock_complete.return_value = "The correct answer is B because…\n\nYou picked A — the trap."
            result = await grade_mcq_answer(
                db,
                question="Q?",
                options=["A", "B"],
                correct_index=1,
                selected_index=0,
                explanation="",
                document_context="",
            )
        assert result["is_correct"] is False
        assert "correct answer" in result["feedback"].lower()
        assert result["feedback_source"] == "llm"
        mock_complete.assert_called_once()

    asyncio.run(run())


def test_grade_mcq_answer_precomputed_skips_llm() -> None:
    """Option #4: a coached option returns instantly with ZERO LLM calls."""
    db = MagicMock()

    async def run() -> None:
        with patch("app.graphs.mcq_graph.complete_chat", new_callable=AsyncMock) as mock_complete:
            result = await grade_mcq_answer(
                db,
                question="Q?",
                options=["A", "B", "C"],
                correct_index=1,
                selected_index=2,
                option_feedback={"1": "Right one.", "2": "You picked C — the classic trap."},
            )
        assert result["is_correct"] is False
        assert result["feedback"] == "You picked C — the classic trap."
        assert result["feedback_source"] == "precomputed"
        mock_complete.assert_not_called()  # the whole point: no LLM on the answer path

    asyncio.run(run())


def test_grade_mcq_answer_precomputed_miss_falls_through_to_llm() -> None:
    """A coached map missing the chosen option still grades live (then warms later)."""
    db = MagicMock()

    async def run() -> None:
        with patch("app.graphs.mcq_graph.complete_chat", new_callable=AsyncMock) as mock_complete:
            mock_complete.return_value = "Lead idea.\n\nWhy your pick misses."
            result = await grade_mcq_answer(
                db,
                question="Q?",
                options=["A", "B", "C"],
                correct_index=1,
                selected_index=0,
                option_feedback={"1": "Right one."},  # option 0 not coached
            )
        assert result["feedback_source"] == "llm"
        mock_complete.assert_called_once()

    asyncio.run(run())


def test_generate_option_feedback_parses_map() -> None:
    from app.services import option_feedback as of

    db = MagicMock()
    blob = '```json\n{"0": "A is the trap.", "1": "B is right and here is why."}\n```'
    with patch.object(of, "_parse_mcq_json", wraps=of._parse_mcq_json):
        with patch("app.services.mcq_quality._complete_chat_sync", return_value=blob):
            out = of.generate_option_feedback(
                db, question="Q?", options=["A", "B"], correct_index=1, explanation="Because B."
            )
    assert out == {"0": "A is the trap.", "1": "B is right and here is why."}


def test_grade_verdict_is_pure_and_instant() -> None:
    """The verdict-first payload: correct + correct_index + explanation, no LLM/DB."""
    from app.graphs.mcq_graph import grade_verdict

    single = {"options": ["a", "b", "c"], "correct_index": 1, "explanation": "Because b."}
    assert grade_verdict(single, 1)["correct"] is True
    wrong = grade_verdict(single, 2)
    assert wrong["correct"] is False
    assert wrong["correct_index"] == 1
    assert wrong["explanation"] == "Because b."

    multi = {"options": ["a", "b", "c"], "correct_index": 0, "correct_indices": [0, 2]}
    assert grade_verdict(multi, 0, [0, 2])["correct"] is True   # exact set
    assert grade_verdict(multi, 0, [0])["correct"] is False     # partial
    assert grade_verdict(multi, 0, [0, 2])["correct_indices"] == [0, 2]


def test_generate_option_feedback_partial_map_rejected() -> None:
    """A map that doesn't cover every option is dropped (no silent half-coaching)."""
    from app.services import option_feedback as of

    db = MagicMock()
    blob = '{"0": "only one option covered"}'
    with patch("app.services.mcq_quality._complete_chat_sync", return_value=blob):
        out = of.generate_option_feedback(
            db, question="Q?", options=["A", "B", "C"], correct_index=2, explanation=""
        )
    assert out == {}


def test_grade_mcq_answer_multi_select_all_or_nothing() -> None:
    """Multi-select grades correct only when the chosen set exactly equals the key."""
    db = MagicMock()

    async def run(selected: list[int]) -> bool:
        with patch("app.graphs.mcq_graph.complete_chat", new_callable=AsyncMock) as mock_complete:
            mock_complete.return_value = "Lead idea.\n\nSecond paragraph."
            result = await grade_mcq_answer(
                db,
                question="Which apply?",
                options=["A", "B", "C", "D"],
                correct_index=0,
                selected_index=selected[0] if selected else -1,
                correct_indices=[0, 2],
                selected_indices=selected,
                explanation="",
                document_context="",
            )
        return result["is_correct"]

    assert asyncio.run(run([0, 2])) is True           # exact set
    assert asyncio.run(run([2, 0])) is True            # order-independent
    assert asyncio.run(run([0])) is False              # missing one
    assert asyncio.run(run([0, 2, 3])) is False        # one extra
    assert asyncio.run(run([1, 3])) is False           # wrong set


def test_grade_mcq_answer_llm_failure_falls_back() -> None:
    """A provider error must never break grading — the fallback feedback is returned."""
    db = MagicMock()

    async def run() -> None:
        with patch("app.graphs.mcq_graph.complete_chat", new_callable=AsyncMock) as mock_complete:
            mock_complete.side_effect = RuntimeError("provider down")
            result = await grade_mcq_answer(
                db,
                question="Q?",
                options=["A", "B"],
                correct_index=1,
                selected_index=0,
                explanation="",
                document_context="",
            )
        assert result["is_correct"] is False
        assert result["feedback"]  # non-empty fallback
        mock_complete.assert_called_once()

    asyncio.run(run())
