---
- name: Install local-path provisioner
  ansible.builtin.command: >-
    kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.31/deploy/local-path-storage.yaml
  environment: { KUBECONFIG: /etc/kubernetes/admin.conf }
  register: lpp
  changed_when: "'created' in lpp.stdout"

- name: Make local-path the default StorageClass (idempotent annotation)
  ansible.builtin.command: >-
    kubectl annotate storageclass local-path
    storageclass.kubernetes.io/is-default-class=true --overwrite
  environment: { KUBECONFIG: /etc/kubernetes/admin.conf }
  changed_when: true
