replicaCount: 2
namespace: zivo
image:
  repository: ghcr.io/benitojd/zivo-auth
  tag: Zivo_0.1.351
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  port: 8000
ingress:
  enabled: true
  className: traefik
  host: auth.zivo.fyi
  tls: true
  entrypoint: websecure
  tlsSecret: zivo-auth-tls
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: "500m"
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
podDisruptionBudget:
  enabled: true
  minAvailable: 1
