namespace: zivo
replicaCount: 2
image:
  repository: ghcr.io/benitojd/zivo-api
  tag: Zivo_0.1.58
  pullPolicy: IfNotPresent
secretName: zivo-secrets
imagePullSecrets:
  - name: ghcr-cred
workloads:
  io:
    enabled: true
    replicaCount: 3
    command: ["python", "run_eta_worker_async.py"]
    env:
      ETA_WORKER_WORKLOADS: io
  cpu:
    enabled: true
    command: ["python", "run_eta_worker_cpu.py"]
    env:
      ETA_WORKER_WORKLOADS: cpu
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
podDisruptionBudget:
  enabled: true
  minAvailable: 1
